import { useMemo, useState } from 'react';
import { ArrowUpRight, BookOpen, Clock3, Filter, Search, Sparkles, SlidersHorizontal } from 'lucide-react';
import { Link } from 'wouter';
import { getListQuestionSetsQueryKey, getListTracksQueryKey, useListQuestionSets, useListTracks } from '@workspace/api-client-react';
import { AppShell, LoadingBlocks, PageHeader, QueryState } from '@/components/AppShell';

export default function PracticePage() {
  const [search, setSearch] = useState('');
  const [track, setTrack] = useState('all');
  const [difficulty, setDifficulty] = useState('all');
  const tracksQuery = useListTracks({ query: { queryKey: getListTracksQueryKey() } });
  const trackParams = track === 'all' ? undefined : { track };
  const setsQuery = useListQuestionSets(trackParams, { query: { queryKey: getListQuestionSetsQueryKey(trackParams) } });
  const sets = useMemo(() => (setsQuery.data ?? []).filter((set) => `${set.title} ${set.subtitle} ${set.track}`.toLowerCase().includes(search.toLowerCase())).filter((set) => difficulty === 'all' || set.difficulty.toLowerCase() === difficulty), [setsQuery.data, search, difficulty]);

  return <AppShell><PageHeader eyebrow="Practice room" title="Choose your pressure." description="Build exam stamina one deliberate set at a time. Filter by track, find your gap, and start before your brain negotiates." action={<div className="hidden items-center gap-2 rounded-xl border border-border bg-card px-3 py-2 text-xs text-muted-foreground sm:flex"><SlidersHorizontal className="h-4 w-4 text-primary" /> Adaptive sets on</div>} />
    <div className="mb-8 grid gap-3 lg:grid-cols-[1fr_auto]">
      <label className="group flex items-center gap-3 rounded-xl border border-border bg-card px-4 py-3 shadow-sm transition-colors focus-within:border-primary"><Search className="h-4 w-4 text-muted-foreground group-focus-within:text-primary" /><input value={search} onChange={(event) => setSearch(event.target.value)} data-testid="input-search-question-sets" placeholder="Search sets, topics, or exam tracks" className="w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground/70" /></label>
      <div className="flex gap-2 overflow-x-auto pb-1">
        <select value={track} onChange={(event) => setTrack(event.target.value)} data-testid="select-filter-track" className="rounded-xl border border-border bg-card px-3 py-2 text-sm font-semibold outline-none focus:border-primary"><option value="all">All tracks</option>{(tracksQuery.data ?? []).map((item) => <option key={item.id} value={item.name}>{item.shortName}</option>)}</select>
        <select value={difficulty} onChange={(event) => setDifficulty(event.target.value)} data-testid="select-filter-difficulty" className="rounded-xl border border-border bg-card px-3 py-2 text-sm font-semibold outline-none focus:border-primary"><option value="all">All levels</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select>
      </div>
    </div>
    <section className="mb-10">
      <div className="mb-4 flex items-center justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.18em] text-muted-foreground">Exam tracks</p><h2 className="mt-1 text-xl font-extrabold tracking-tight">Pick your arena</h2></div><Filter className="h-5 w-5 text-muted-foreground" /></div>
      {tracksQuery.isLoading ? <LoadingBlocks count={3} /> : tracksQuery.isError ? <QueryState error onRetry={() => void tracksQuery.refetch()} /> : <div className="grid gap-3 md:grid-cols-3">{(tracksQuery.data ?? []).map((item, index) => <button type="button" key={item.id} onClick={() => setTrack(item.name)} data-testid={`button-track-${item.id}`} className={`stagger-in stagger-${index + 1} group relative overflow-hidden rounded-2xl border p-5 text-left transition-all duration-300 hover:-translate-y-1 hover:shadow-lg ${track === item.name ? 'border-primary bg-primary text-primary-foreground shadow-lg shadow-primary/15' : 'border-border bg-card hover:border-primary/40'}`}><div className="absolute -right-5 -top-5 h-20 w-20 rounded-full opacity-20" style={{ backgroundColor: item.color }} /><div className="relative"><div className="mb-7 flex items-start justify-between"><span className={`font-mono-ui text-xs font-medium ${track === item.name ? 'text-accent' : 'text-primary'}`}>{item.shortName}</span><ArrowUpRight className="h-4 w-4 opacity-50 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></div><h3 className="text-lg font-extrabold">{item.name}</h3><p className={`mt-1 line-clamp-2 text-xs leading-relaxed ${track === item.name ? 'text-primary-foreground/65' : 'text-muted-foreground'}`}>{item.description}</p><p className={`mt-5 font-mono-ui text-[10px] uppercase tracking-wider ${track === item.name ? 'text-primary-foreground/55' : 'text-muted-foreground'}`}>{item.questionCount} questions in rotation</p></div></button>)}</div>}
    </section>
    <section><div className="mb-4 flex items-end justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.18em] text-muted-foreground">Question sets</p><h2 className="mt-1 text-xl font-extrabold tracking-tight">{sets.length} sets ready</h2></div><span className="hidden items-center gap-1 text-xs text-muted-foreground sm:flex"><Sparkles className="h-3.5 w-3.5 text-accent-foreground" /> Curated for your target</span></div>
      <QueryState error={setsQuery.isError} onRetry={() => void setsQuery.refetch()} />
      {setsQuery.isLoading ? <LoadingBlocks count={6} /> : sets.length === 0 ? <div className="rounded-2xl border border-dashed border-border bg-card p-12 text-center"><BookOpen className="mx-auto h-8 w-8 text-muted-foreground" /><p className="mt-4 font-semibold">No sets match that filter.</p><p className="mt-1 text-sm text-muted-foreground">Try widening the arena and keep the momentum.</p><button type="button" onClick={() => { setSearch(''); setTrack('all'); setDifficulty('all'); }} data-testid="button-clear-filters" className="mt-5 rounded-lg bg-primary px-4 py-2 text-sm font-bold text-primary-foreground">Clear filters</button></div> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{sets.map((set, index) => <article key={set.id} data-testid={`card-question-set-${set.id}`} className={`stagger-in stagger-${(index % 5) + 1} group relative overflow-hidden rounded-2xl border border-border bg-card p-5 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-primary/30 hover:shadow-xl`}><div className="absolute inset-x-0 top-0 h-1" style={{ backgroundColor: set.accent }} /><div className="mb-7 flex items-center justify-between"><span className="rounded-md bg-muted px-2 py-1 font-mono-ui text-[10px] uppercase tracking-wider text-muted-foreground">{set.track}</span><span className={`font-mono-ui text-[10px] uppercase tracking-wider ${set.difficulty.toLowerCase() === 'hard' ? 'text-destructive' : 'text-muted-foreground'}`}>{set.difficulty}</span></div><h3 className="text-lg font-extrabold tracking-tight">{set.title}</h3><p className="mt-1 min-h-10 text-xs leading-relaxed text-muted-foreground">{set.subtitle}</p><div className="mt-5 flex gap-4 border-t border-border pt-4 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><BookOpen className="h-3.5 w-3.5" /> {set.questions} Qs</span><span className="flex items-center gap-1.5"><Clock3 className="h-3.5 w-3.5" /> {set.duration} min</span></div><div className="mt-4 flex items-center justify-between"><div className="flex items-center gap-2"><div className="h-1.5 w-20 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${set.completion}%` }} /></div><span className="font-mono-ui text-[10px] text-muted-foreground">{set.completion}%</span></div><Link href={`/practice/${set.id}`} data-testid={`link-start-set-${set.id}`} className="flex items-center gap-1 text-xs font-bold text-primary transition-all group-hover:gap-2">Enter set <ArrowUpRight className="h-3.5 w-3.5" /></Link></div></article>)}</div>}
    </section>
  </AppShell>;
}