import { useState } from 'react';
import { Bell, Check, ChevronDown, MonitorCog, Moon, Save, Target, UserRound } from 'lucide-react';
import { AppShell, PageHeader } from '@/components/AppShell';

export default function SettingsPage() {
  const [target, setTarget] = useState('UPSC CSE');
  const [dailyGoal, setDailyGoal] = useState('45');
  const [saved, setSaved] = useState(false);
  const [notifications, setNotifications] = useState(true);
  const [compact, setCompact] = useState(false);
  const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 2200); };
  return <AppShell><PageHeader eyebrow="Control room" title="Tune your training." description="Set the target, shape the rhythm, and make the arena fit how you actually study." action={saved ? <div className="flex items-center gap-2 rounded-xl bg-emerald-100 px-3 py-2 text-xs font-bold text-emerald-700"><Check className="h-4 w-4" /> Preferences saved</div> : <button type="button" onClick={save} data-testid="button-save-settings-top" className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground transition-all hover:-translate-y-0.5"><Save className="h-4 w-4" /> Save changes</button>} />
    <div className="grid max-w-5xl gap-6 lg:grid-cols-[1.2fr_.8fr]">
      <div className="space-y-6">
        <section className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-7"><div className="mb-7 flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Target className="h-5 w-5" /></div><div><h2 className="text-lg font-extrabold">Target exam</h2><p className="mt-1 text-sm text-muted-foreground">Your recommendations and leaderboard context follow this choice.</p></div></div><label className="mb-2 block font-mono-ui text-[10px] uppercase tracking-wider text-muted-foreground">Primary target</label><div className="relative"><select value={target} onChange={(event) => setTarget(event.target.value)} data-testid="select-target-exam" className="w-full appearance-none rounded-xl border border-border bg-background px-4 py-3 text-sm font-semibold outline-none transition-colors focus:border-primary"><option>UPSC CSE</option><option>SSC CGL</option><option>GATE Computer Science</option><option>State PSC</option></select><ChevronDown className="pointer-events-none absolute right-4 top-3.5 h-4 w-4 text-muted-foreground" /></div><label className="mt-6 mb-2 block font-mono-ui text-[10px] uppercase tracking-wider text-muted-foreground">Daily focus goal</label><div className="flex items-center gap-3"><input type="range" min="15" max="120" step="15" value={dailyGoal} onChange={(event) => setDailyGoal(event.target.value)} data-testid="input-daily-goal" className="w-full accent-[#5668c9]" /><span className="w-16 rounded-lg bg-muted px-2 py-2 text-center font-mono-ui text-xs">{dailyGoal} min</span></div></section>
        <section className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-7"><div className="mb-7 flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-accent/30 text-[#9a700d]"><Bell className="h-5 w-5" /></div><div><h2 className="text-lg font-extrabold">Signals</h2><p className="mt-1 text-sm text-muted-foreground">Choose what deserves a tap on the shoulder.</p></div></div><ToggleRow icon={Bell} title="Daily practice reminder" description="A quiet nudge at your preferred study hour." checked={notifications} onChange={() => setNotifications(!notifications)} testId="switch-practice-reminder" /><ToggleRow icon={MonitorCog} title="Compact question layout" description="Keep more context visible while solving." checked={compact} onChange={() => setCompact(!compact)} testId="switch-compact-layout" /></section>
      </div>
      <aside className="space-y-6"><section className="rounded-2xl bg-sidebar p-6 text-sidebar-foreground shadow-xl"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-accent text-accent-foreground font-bold">AK</div><div><p className="font-bold text-white">Arjun Kapoor</p><p className="font-mono-ui text-[10px] uppercase tracking-wider text-sidebar-foreground/55">Learner profile</p></div></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-xl bg-sidebar-accent p-3"><p className="font-mono-ui text-[10px] uppercase tracking-wider text-sidebar-foreground/50">Target</p><p className="mt-1 text-sm font-bold text-white">{target}</p></div><div className="rounded-xl bg-sidebar-accent p-3"><p className="font-mono-ui text-[10px] uppercase tracking-wider text-sidebar-foreground/50">Mode</p><p className="mt-1 text-sm font-bold text-white">Focused</p></div></div></section><section className="rounded-2xl border border-border bg-card p-6"><UserRound className="h-5 w-5 text-primary" /><h3 className="mt-4 font-extrabold">Profile details</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">Your public learner name and target are visible on the global leaderboard.</p><button type="button" onClick={save} data-testid="button-save-profile" className="mt-5 w-full rounded-xl border border-border px-4 py-2.5 text-sm font-bold transition-colors hover:bg-muted">Save profile</button></section><div className="flex items-center gap-2 px-1 text-xs text-muted-foreground"><Moon className="h-4 w-4" /> Light training room theme is active</div></aside>
    </div>
  </AppShell>;
}

function ToggleRow({ icon: Icon, title, description, checked, onChange, testId }: { icon: typeof Bell; title: string; description: string; checked: boolean; onChange: () => void; testId: string }) {
  return <div className="flex items-center justify-between gap-4 border-t border-border py-4 first:border-t-0 first:pt-0 last:pb-0"><div className="flex items-start gap-3"><Icon className="mt-0.5 h-4 w-4 text-muted-foreground" /><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{description}</p></div></div><button type="button" role="switch" aria-checked={checked} onClick={onChange} data-testid={testId} className={`relative h-6 w-11 shrink-0 rounded-full transition-colors ${checked ? 'bg-primary' : 'bg-muted'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${checked ? 'translate-x-6' : 'translate-x-1'}`} /></button></div>;
}